version: 0.2

env:
  exported-variables:
    - RELEASE_PKG_FILE
    - MVN_VERSION_ID
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean verify
  post_build:
    commands:
      - export RELEASE_PKG_FILE=$(ls repository/target/com.rockwellcollins.atc.agree.repository-*.zip)
      - echo Built $RELEASE_PKG_FILE
      - export MVN_VERSION_ID=$(ls repository/target/repository/plugins/com.rockwellcollins.atc.agree_*.jar | grep -o "[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+\\.[0-9]\\{12\\}")
      - echo Version Id: $MVN_VERSION_ID
      - echo Build completed on `date`
artifacts:
  files:
    - repository/target/repository/**/*
