/*
 * Copyright (c) 2023, Collins Aerospace.
 * Developed with the sponsorship of Defense Advanced Research Projects Agency (DARPA).
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this data, 
 * including any software or models in source or binary form, as well as any drawings, specifications, 
 * and documentation (collectively "the Data"), to deal in the Data without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Data, and to permit persons to whom the Data is furnished to do so, 
 * subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Data.
 * 
 * THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
 * LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 * IN NO EVENT SHALL THE AUTHORS, SPONSORS, DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE LIABLE 
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE DATA.
 *
 * Generated by Xtext version 2.30.0.
 */

package com.rockwellcollins.atc.agree.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import com.rockwellcollins.atc.agree.ide.contentassist.antlr.internal.InternalAgreeParser;
import com.rockwellcollins.atc.agree.services.AgreeGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class AgreeParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(AgreeGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, AgreeGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getNamedElementAccess().getAlternatives(), "rule__NamedElement__Alternatives");
			builder.put(grammarAccess.getElementAccess().getAlternatives(), "rule__Element__Alternatives");
			builder.put(grammarAccess.getSpecStatementAccess().getAlternatives(), "rule__SpecStatement__Alternatives");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getAlternatives(), "rule__NamedSpecStatement__Alternatives");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getAlternatives_0_5(), "rule__NamedSpecStatement__Alternatives_0_5");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getAlternatives_1_5(), "rule__NamedSpecStatement__Alternatives_1_5");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getAlternatives_2_3(), "rule__NamedSpecStatement__Alternatives_2_3");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getAlternatives_3_5(), "rule__NamedSpecStatement__Alternatives_3_5");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getAlternatives_4_5(), "rule__NamedSpecStatement__Alternatives_4_5");
			builder.put(grammarAccess.getPatternStatementAccess().getAlternatives(), "rule__PatternStatement__Alternatives");
			builder.put(grammarAccess.getWhenStatementAccess().getAlternatives(), "rule__WhenStatement__Alternatives");
			builder.put(grammarAccess.getWheneverStatementAccess().getAlternatives(), "rule__WheneverStatement__Alternatives");
			builder.put(grammarAccess.getWheneverStatementAccess().getAlternatives_0_0_0_6(), "rule__WheneverStatement__Alternatives_0_0_0_6");
			builder.put(grammarAccess.getWheneverStatementAccess().getAlternatives_1_0_0_7(), "rule__WheneverStatement__Alternatives_1_0_0_7");
			builder.put(grammarAccess.getRealTimeStatementAccess().getAlternatives(), "rule__RealTimeStatement__Alternatives");
			builder.put(grammarAccess.getTimeIntervalAccess().getAlternatives(), "rule__TimeInterval__Alternatives");
			builder.put(grammarAccess.getSynchStatementAccess().getAlternatives(), "rule__SynchStatement__Alternatives");
			builder.put(grammarAccess.getSynchStatementAccess().getSimAlternatives_0_5_0(), "rule__SynchStatement__SimAlternatives_0_5_0");
			builder.put(grammarAccess.getAbstractionAccess().getAlternatives(), "rule__Abstraction__Alternatives");
			builder.put(grammarAccess.getNodeStmtAccess().getAlternatives(), "rule__NodeStmt__Alternatives");
			builder.put(grammarAccess.getBaseTypeAccess().getAlternatives(), "rule__BaseType__Alternatives");
			builder.put(grammarAccess.getBaseTypeAccess().getRangeLowAlternatives_0_2_2_0(), "rule__BaseType__RangeLowAlternatives_0_2_2_0");
			builder.put(grammarAccess.getBaseTypeAccess().getRangeHighAlternatives_0_2_5_0(), "rule__BaseType__RangeHighAlternatives_0_2_5_0");
			builder.put(grammarAccess.getPrimTypesAccess().getAlternatives(), "rule__PrimTypes__Alternatives");
			builder.put(grammarAccess.getForallExprAccess().getAlternatives(), "rule__ForallExpr__Alternatives");
			builder.put(grammarAccess.getExistsExprAccess().getAlternatives(), "rule__ExistsExpr__Alternatives");
			builder.put(grammarAccess.getFlatmapExprAccess().getAlternatives(), "rule__FlatmapExpr__Alternatives");
			builder.put(grammarAccess.getFoldLeftExprAccess().getAlternatives(), "rule__FoldLeftExpr__Alternatives");
			builder.put(grammarAccess.getFoldRightExprAccess().getAlternatives(), "rule__FoldRightExpr__Alternatives");
			builder.put(grammarAccess.getRelateOpAccess().getAlternatives(), "rule__RelateOp__Alternatives");
			builder.put(grammarAccess.getAddSubExprAccess().getOpAlternatives_1_0_0_1_0(), "rule__AddSubExpr__OpAlternatives_1_0_0_1_0");
			builder.put(grammarAccess.getMultDivExprAccess().getOpAlternatives_1_0_0_1_0(), "rule__MultDivExpr__OpAlternatives_1_0_0_1_0");
			builder.put(grammarAccess.getUnaryExprAccess().getAlternatives(), "rule__UnaryExpr__Alternatives");
			builder.put(grammarAccess.getUnaryExprAccess().getOpAlternatives_0_1_0(), "rule__UnaryExpr__OpAlternatives_0_1_0");
			builder.put(grammarAccess.getIfThenElseExprAccess().getAlternatives(), "rule__IfThenElseExpr__Alternatives");
			builder.put(grammarAccess.getComponentRefAccess().getAlternatives(), "rule__ComponentRef__Alternatives");
			builder.put(grammarAccess.getPreDefFnExprAccess().getAlternatives(), "rule__PreDefFnExpr__Alternatives");
			builder.put(grammarAccess.getTermExprAccess().getAlternatives(), "rule__TermExpr__Alternatives");
			builder.put(grammarAccess.getReservedVarTagAccess().getAlternatives(), "rule__ReservedVarTag__Alternatives");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getAlternatives_1(), "rule__ContainedPropertyAssociation__Alternatives_1");
			builder.put(grammarAccess.getPropertyAssociationAccess().getAlternatives_1(), "rule__PropertyAssociation__Alternatives_1");
			builder.put(grammarAccess.getPropertyExpressionAccess().getAlternatives(), "rule__PropertyExpression__Alternatives");
			builder.put(grammarAccess.getBooleanLiteralAccess().getAlternatives_1(), "rule__BooleanLiteral__Alternatives_1");
			builder.put(grammarAccess.getPlusMinusAccess().getAlternatives(), "rule__PlusMinus__Alternatives");
			builder.put(grammarAccess.getSignedIntAccess().getAlternatives_0(), "rule__SignedInt__Alternatives_0");
			builder.put(grammarAccess.getSignedRealAccess().getAlternatives_0(), "rule__SignedReal__Alternatives_0");
			builder.put(grammarAccess.getNumAltAccess().getAlternatives(), "rule__NumAlt__Alternatives");
			builder.put(grammarAccess.getAgreeLibraryAccess().getGroup(), "rule__AgreeLibrary__Group__0");
			builder.put(grammarAccess.getAgreeSubclauseAccess().getGroup(), "rule__AgreeSubclause__Group__0");
			builder.put(grammarAccess.getAgreeContractAccess().getGroup(), "rule__AgreeContract__Group__0");
			builder.put(grammarAccess.getSpecStatementAccess().getGroup_1(), "rule__SpecStatement__Group_1__0");
			builder.put(grammarAccess.getSpecStatementAccess().getGroup_2(), "rule__SpecStatement__Group_2__0");
			builder.put(grammarAccess.getSpecStatementAccess().getGroup_3(), "rule__SpecStatement__Group_3__0");
			builder.put(grammarAccess.getSpecStatementAccess().getGroup_4(), "rule__SpecStatement__Group_4__0");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getGroup_0(), "rule__NamedSpecStatement__Group_0__0");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getGroup_1(), "rule__NamedSpecStatement__Group_1__0");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getGroup_2(), "rule__NamedSpecStatement__Group_2__0");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getGroup_2_2(), "rule__NamedSpecStatement__Group_2_2__0");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getGroup_3(), "rule__NamedSpecStatement__Group_3__0");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getGroup_4(), "rule__NamedSpecStatement__Group_4__0");
			builder.put(grammarAccess.getPatternStatementAccess().getGroup_1(), "rule__PatternStatement__Group_1__0");
			builder.put(grammarAccess.getWhenStatementAccess().getGroup_0(), "rule__WhenStatement__Group_0__0");
			builder.put(grammarAccess.getWhenStatementAccess().getGroup_0_0(), "rule__WhenStatement__Group_0_0__0");
			builder.put(grammarAccess.getWhenStatementAccess().getGroup_0_0_0(), "rule__WhenStatement__Group_0_0_0__0");
			builder.put(grammarAccess.getWhenStatementAccess().getGroup_0_6(), "rule__WhenStatement__Group_0_6__0");
			builder.put(grammarAccess.getWhenStatementAccess().getGroup_1(), "rule__WhenStatement__Group_1__0");
			builder.put(grammarAccess.getWhenStatementAccess().getGroup_1_0(), "rule__WhenStatement__Group_1_0__0");
			builder.put(grammarAccess.getWhenStatementAccess().getGroup_1_0_0(), "rule__WhenStatement__Group_1_0_0__0");
			builder.put(grammarAccess.getWheneverStatementAccess().getGroup_0(), "rule__WheneverStatement__Group_0__0");
			builder.put(grammarAccess.getWheneverStatementAccess().getGroup_0_0(), "rule__WheneverStatement__Group_0_0__0");
			builder.put(grammarAccess.getWheneverStatementAccess().getGroup_0_0_0(), "rule__WheneverStatement__Group_0_0_0__0");
			builder.put(grammarAccess.getWheneverStatementAccess().getGroup_0_1(), "rule__WheneverStatement__Group_0_1__0");
			builder.put(grammarAccess.getWheneverStatementAccess().getGroup_1(), "rule__WheneverStatement__Group_1__0");
			builder.put(grammarAccess.getWheneverStatementAccess().getGroup_1_0(), "rule__WheneverStatement__Group_1_0__0");
			builder.put(grammarAccess.getWheneverStatementAccess().getGroup_1_0_0(), "rule__WheneverStatement__Group_1_0_0__0");
			builder.put(grammarAccess.getWheneverStatementAccess().getGroup_1_1(), "rule__WheneverStatement__Group_1_1__0");
			builder.put(grammarAccess.getWheneverStatementAccess().getGroup_2(), "rule__WheneverStatement__Group_2__0");
			builder.put(grammarAccess.getWheneverStatementAccess().getGroup_2_0(), "rule__WheneverStatement__Group_2_0__0");
			builder.put(grammarAccess.getWheneverStatementAccess().getGroup_2_0_0(), "rule__WheneverStatement__Group_2_0_0__0");
			builder.put(grammarAccess.getWheneverStatementAccess().getGroup_2_1(), "rule__WheneverStatement__Group_2_1__0");
			builder.put(grammarAccess.getWheneverStatementAccess().getGroup_3(), "rule__WheneverStatement__Group_3__0");
			builder.put(grammarAccess.getWheneverStatementAccess().getGroup_3_0(), "rule__WheneverStatement__Group_3_0__0");
			builder.put(grammarAccess.getWheneverStatementAccess().getGroup_3_0_0(), "rule__WheneverStatement__Group_3_0_0__0");
			builder.put(grammarAccess.getWheneverStatementAccess().getGroup_3_3(), "rule__WheneverStatement__Group_3_3__0");
			builder.put(grammarAccess.getRealTimeStatementAccess().getGroup_0(), "rule__RealTimeStatement__Group_0__0");
			builder.put(grammarAccess.getRealTimeStatementAccess().getGroup_0_0(), "rule__RealTimeStatement__Group_0_0__0");
			builder.put(grammarAccess.getRealTimeStatementAccess().getGroup_0_0_0(), "rule__RealTimeStatement__Group_0_0_0__0");
			builder.put(grammarAccess.getRealTimeStatementAccess().getGroup_0_2(), "rule__RealTimeStatement__Group_0_2__0");
			builder.put(grammarAccess.getRealTimeStatementAccess().getGroup_1(), "rule__RealTimeStatement__Group_1__0");
			builder.put(grammarAccess.getRealTimeStatementAccess().getGroup_1_0(), "rule__RealTimeStatement__Group_1_0__0");
			builder.put(grammarAccess.getRealTimeStatementAccess().getGroup_1_0_0(), "rule__RealTimeStatement__Group_1_0_0__0");
			builder.put(grammarAccess.getRealTimeStatementAccess().getGroup_1_4(), "rule__RealTimeStatement__Group_1_4__0");
			builder.put(grammarAccess.getTimeIntervalAccess().getGroup_0(), "rule__TimeInterval__Group_0__0");
			builder.put(grammarAccess.getTimeIntervalAccess().getGroup_0_0(), "rule__TimeInterval__Group_0_0__0");
			builder.put(grammarAccess.getTimeIntervalAccess().getGroup_1(), "rule__TimeInterval__Group_1__0");
			builder.put(grammarAccess.getTimeIntervalAccess().getGroup_1_0(), "rule__TimeInterval__Group_1_0__0");
			builder.put(grammarAccess.getTimeIntervalAccess().getGroup_2(), "rule__TimeInterval__Group_2__0");
			builder.put(grammarAccess.getTimeIntervalAccess().getGroup_2_0(), "rule__TimeInterval__Group_2_0__0");
			builder.put(grammarAccess.getTimeIntervalAccess().getGroup_3(), "rule__TimeInterval__Group_3__0");
			builder.put(grammarAccess.getTimeIntervalAccess().getGroup_3_0(), "rule__TimeInterval__Group_3_0__0");
			builder.put(grammarAccess.getSynchStatementAccess().getGroup_0(), "rule__SynchStatement__Group_0__0");
			builder.put(grammarAccess.getSynchStatementAccess().getGroup_0_4(), "rule__SynchStatement__Group_0_4__0");
			builder.put(grammarAccess.getSynchStatementAccess().getGroup_1(), "rule__SynchStatement__Group_1__0");
			builder.put(grammarAccess.getSynchStatementAccess().getGroup_1_3(), "rule__SynchStatement__Group_1_3__0");
			builder.put(grammarAccess.getSynchStatementAccess().getGroup_2(), "rule__SynchStatement__Group_2__0");
			builder.put(grammarAccess.getSynchStatementAccess().getGroup_2_4(), "rule__SynchStatement__Group_2_4__0");
			builder.put(grammarAccess.getSynchStatementAccess().getGroup_3(), "rule__SynchStatement__Group_3__0");
			builder.put(grammarAccess.getSynchStatementAccess().getGroup_4(), "rule__SynchStatement__Group_4__0");
			builder.put(grammarAccess.getOrderStatementAccess().getGroup(), "rule__OrderStatement__Group__0");
			builder.put(grammarAccess.getOrderStatementAccess().getGroup_3(), "rule__OrderStatement__Group_3__0");
			builder.put(grammarAccess.getPropertyStatementAccess().getGroup(), "rule__PropertyStatement__Group__0");
			builder.put(grammarAccess.getConstStatementAccess().getGroup(), "rule__ConstStatement__Group__0");
			builder.put(grammarAccess.getEqStatementAccess().getGroup(), "rule__EqStatement__Group__0");
			builder.put(grammarAccess.getEqStatementAccess().getGroup_1(), "rule__EqStatement__Group_1__0");
			builder.put(grammarAccess.getEqStatementAccess().getGroup_1_1(), "rule__EqStatement__Group_1_1__0");
			builder.put(grammarAccess.getEqStatementAccess().getGroup_2(), "rule__EqStatement__Group_2__0");
			builder.put(grammarAccess.getInputStatementAccess().getGroup(), "rule__InputStatement__Group__0");
			builder.put(grammarAccess.getInputStatementAccess().getGroup_1(), "rule__InputStatement__Group_1__0");
			builder.put(grammarAccess.getInputStatementAccess().getGroup_1_1(), "rule__InputStatement__Group_1_1__0");
			builder.put(grammarAccess.getAssignStatementAccess().getGroup(), "rule__AssignStatement__Group__0");
			builder.put(grammarAccess.getFnDefAccess().getGroup(), "rule__FnDef__Group__0");
			builder.put(grammarAccess.getFnDefAccess().getGroup_4(), "rule__FnDef__Group_4__0");
			builder.put(grammarAccess.getLibraryFnDefAccess().getGroup(), "rule__LibraryFnDef__Group__0");
			builder.put(grammarAccess.getLibraryFnDefAccess().getGroup_4(), "rule__LibraryFnDef__Group_4__0");
			builder.put(grammarAccess.getUninterpretedFnDefAccess().getGroup(), "rule__UninterpretedFnDef__Group__0");
			builder.put(grammarAccess.getUninterpretedFnDefAccess().getGroup_4(), "rule__UninterpretedFnDef__Group_4__0");
			builder.put(grammarAccess.getLinearizationDefAccess().getGroup(), "rule__LinearizationDef__Group__0");
			builder.put(grammarAccess.getLinearizationDefAccess().getGroup_4(), "rule__LinearizationDef__Group_4__0");
			builder.put(grammarAccess.getLinearizationDefAccess().getGroup_9(), "rule__LinearizationDef__Group_9__0");
			builder.put(grammarAccess.getLinearizationDefAccess().getGroup_11(), "rule__LinearizationDef__Group_11__0");
			builder.put(grammarAccess.getLinearizationIntervalAccess().getGroup(), "rule__LinearizationInterval__Group__0");
			builder.put(grammarAccess.getNodeDefAccess().getGroup(), "rule__NodeDef__Group__0");
			builder.put(grammarAccess.getNodeDefAccess().getGroup_3(), "rule__NodeDef__Group_3__0");
			builder.put(grammarAccess.getNodeDefAccess().getGroup_3_1(), "rule__NodeDef__Group_3_1__0");
			builder.put(grammarAccess.getNodeDefAccess().getGroup_7(), "rule__NodeDef__Group_7__0");
			builder.put(grammarAccess.getNodeDefAccess().getGroup_7_1(), "rule__NodeDef__Group_7_1__0");
			builder.put(grammarAccess.getNodeBodyExprAccess().getGroup(), "rule__NodeBodyExpr__Group__0");
			builder.put(grammarAccess.getNodeBodyExprAccess().getGroup_0(), "rule__NodeBodyExpr__Group_0__0");
			builder.put(grammarAccess.getNodeBodyExprAccess().getGroup_0_1(), "rule__NodeBodyExpr__Group_0_1__0");
			builder.put(grammarAccess.getNodeStmtAccess().getGroup_0(), "rule__NodeStmt__Group_0__0");
			builder.put(grammarAccess.getNodeStmtAccess().getGroup_0_2(), "rule__NodeStmt__Group_0_2__0");
			builder.put(grammarAccess.getNodeStmtAccess().getGroup_1(), "rule__NodeStmt__Group_1__0");
			builder.put(grammarAccess.getArgAccess().getGroup(), "rule__Arg__Group__0");
			builder.put(grammarAccess.getArgAccess().getGroup_0(), "rule__Arg__Group_0__0");
			builder.put(grammarAccess.getTypeAccess().getGroup(), "rule__Type__Group__0");
			builder.put(grammarAccess.getTypeAccess().getGroup_1(), "rule__Type__Group_1__0");
			builder.put(grammarAccess.getTypeAccess().getGroup_1_0(), "rule__Type__Group_1_0__0");
			builder.put(grammarAccess.getBaseTypeAccess().getGroup_0(), "rule__BaseType__Group_0__0");
			builder.put(grammarAccess.getBaseTypeAccess().getGroup_0_2(), "rule__BaseType__Group_0_2__0");
			builder.put(grammarAccess.getRecordDefAccess().getGroup(), "rule__RecordDef__Group__0");
			builder.put(grammarAccess.getRecordDefAccess().getGroup_5(), "rule__RecordDef__Group_5__0");
			builder.put(grammarAccess.getRecordDefAccess().getGroup_5_1(), "rule__RecordDef__Group_5_1__0");
			builder.put(grammarAccess.getEnumStatementAccess().getGroup(), "rule__EnumStatement__Group__0");
			builder.put(grammarAccess.getEnumStatementAccess().getGroup_5(), "rule__EnumStatement__Group_5__0");
			builder.put(grammarAccess.getForallExprAccess().getGroup_0(), "rule__ForallExpr__Group_0__0");
			builder.put(grammarAccess.getExistsExprAccess().getGroup_0(), "rule__ExistsExpr__Group_0__0");
			builder.put(grammarAccess.getFlatmapExprAccess().getGroup_0(), "rule__FlatmapExpr__Group_0__0");
			builder.put(grammarAccess.getFoldLeftExprAccess().getGroup_0(), "rule__FoldLeftExpr__Group_0__0");
			builder.put(grammarAccess.getFoldRightExprAccess().getGroup_0(), "rule__FoldRightExpr__Group_0__0");
			builder.put(grammarAccess.getArrowExprAccess().getGroup(), "rule__ArrowExpr__Group__0");
			builder.put(grammarAccess.getArrowExprAccess().getGroup_1(), "rule__ArrowExpr__Group_1__0");
			builder.put(grammarAccess.getArrowExprAccess().getGroup_1_0(), "rule__ArrowExpr__Group_1_0__0");
			builder.put(grammarAccess.getArrowExprAccess().getGroup_1_0_0(), "rule__ArrowExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getImpliesExprAccess().getGroup(), "rule__ImpliesExpr__Group__0");
			builder.put(grammarAccess.getImpliesExprAccess().getGroup_1(), "rule__ImpliesExpr__Group_1__0");
			builder.put(grammarAccess.getImpliesExprAccess().getGroup_1_0(), "rule__ImpliesExpr__Group_1_0__0");
			builder.put(grammarAccess.getImpliesExprAccess().getGroup_1_0_0(), "rule__ImpliesExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getEquivExprAccess().getGroup(), "rule__EquivExpr__Group__0");
			builder.put(grammarAccess.getEquivExprAccess().getGroup_1(), "rule__EquivExpr__Group_1__0");
			builder.put(grammarAccess.getEquivExprAccess().getGroup_1_0(), "rule__EquivExpr__Group_1_0__0");
			builder.put(grammarAccess.getEquivExprAccess().getGroup_1_0_0(), "rule__EquivExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getOrExprAccess().getGroup(), "rule__OrExpr__Group__0");
			builder.put(grammarAccess.getOrExprAccess().getGroup_1(), "rule__OrExpr__Group_1__0");
			builder.put(grammarAccess.getOrExprAccess().getGroup_1_0(), "rule__OrExpr__Group_1_0__0");
			builder.put(grammarAccess.getOrExprAccess().getGroup_1_0_0(), "rule__OrExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getAndExprAccess().getGroup(), "rule__AndExpr__Group__0");
			builder.put(grammarAccess.getAndExprAccess().getGroup_1(), "rule__AndExpr__Group_1__0");
			builder.put(grammarAccess.getAndExprAccess().getGroup_1_0(), "rule__AndExpr__Group_1_0__0");
			builder.put(grammarAccess.getAndExprAccess().getGroup_1_0_0(), "rule__AndExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getRelateExprAccess().getGroup(), "rule__RelateExpr__Group__0");
			builder.put(grammarAccess.getRelateExprAccess().getGroup_1(), "rule__RelateExpr__Group_1__0");
			builder.put(grammarAccess.getRelateExprAccess().getGroup_1_0(), "rule__RelateExpr__Group_1_0__0");
			builder.put(grammarAccess.getRelateExprAccess().getGroup_1_0_0(), "rule__RelateExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getAddSubExprAccess().getGroup(), "rule__AddSubExpr__Group__0");
			builder.put(grammarAccess.getAddSubExprAccess().getGroup_1(), "rule__AddSubExpr__Group_1__0");
			builder.put(grammarAccess.getAddSubExprAccess().getGroup_1_0(), "rule__AddSubExpr__Group_1_0__0");
			builder.put(grammarAccess.getAddSubExprAccess().getGroup_1_0_0(), "rule__AddSubExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getMultDivExprAccess().getGroup(), "rule__MultDivExpr__Group__0");
			builder.put(grammarAccess.getMultDivExprAccess().getGroup_1(), "rule__MultDivExpr__Group_1__0");
			builder.put(grammarAccess.getMultDivExprAccess().getGroup_1_0(), "rule__MultDivExpr__Group_1_0__0");
			builder.put(grammarAccess.getMultDivExprAccess().getGroup_1_0_0(), "rule__MultDivExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getPowerExprAccess().getGroup(), "rule__PowerExpr__Group__0");
			builder.put(grammarAccess.getPowerExprAccess().getGroup_1(), "rule__PowerExpr__Group_1__0");
			builder.put(grammarAccess.getPowerExprAccess().getGroup_1_0(), "rule__PowerExpr__Group_1_0__0");
			builder.put(grammarAccess.getPowerExprAccess().getGroup_1_0_0(), "rule__PowerExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getUnaryExprAccess().getGroup_0(), "rule__UnaryExpr__Group_0__0");
			builder.put(grammarAccess.getIfThenElseExprAccess().getGroup_0(), "rule__IfThenElseExpr__Group_0__0");
			builder.put(grammarAccess.getComponentRefAccess().getGroup_0(), "rule__ComponentRef__Group_0__0");
			builder.put(grammarAccess.getPreDefFnExprAccess().getGroup_0(), "rule__PreDefFnExpr__Group_0__0");
			builder.put(grammarAccess.getPreDefFnExprAccess().getGroup_1(), "rule__PreDefFnExpr__Group_1__0");
			builder.put(grammarAccess.getArrayUpdateExprAccess().getGroup(), "rule__ArrayUpdateExpr__Group__0");
			builder.put(grammarAccess.getArrayUpdateExprAccess().getGroup_1(), "rule__ArrayUpdateExpr__Group_1__0");
			builder.put(grammarAccess.getArrayUpdateExprAccess().getGroup_1_0(), "rule__ArrayUpdateExpr__Group_1_0__0");
			builder.put(grammarAccess.getArrayUpdateExprAccess().getGroup_1_0_0(), "rule__ArrayUpdateExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getArrayUpdateExprAccess().getGroup_1_2(), "rule__ArrayUpdateExpr__Group_1_2__0");
			builder.put(grammarAccess.getRecordUpdateExprAccess().getGroup(), "rule__RecordUpdateExpr__Group__0");
			builder.put(grammarAccess.getRecordUpdateExprAccess().getGroup_1(), "rule__RecordUpdateExpr__Group_1__0");
			builder.put(grammarAccess.getRecordUpdateExprAccess().getGroup_1_0(), "rule__RecordUpdateExpr__Group_1_0__0");
			builder.put(grammarAccess.getArraySubExprAccess().getGroup(), "rule__ArraySubExpr__Group__0");
			builder.put(grammarAccess.getArraySubExprAccess().getGroup_1(), "rule__ArraySubExpr__Group_1__0");
			builder.put(grammarAccess.getArraySubExprAccess().getGroup_1_0(), "rule__ArraySubExpr__Group_1_0__0");
			builder.put(grammarAccess.getTagExprAccess().getGroup(), "rule__TagExpr__Group__0");
			builder.put(grammarAccess.getTagExprAccess().getGroup_1(), "rule__TagExpr__Group_1__0");
			builder.put(grammarAccess.getSelectionExprAccess().getGroup(), "rule__SelectionExpr__Group__0");
			builder.put(grammarAccess.getSelectionExprAccess().getGroup_1(), "rule__SelectionExpr__Group_1__0");
			builder.put(grammarAccess.getSelectionExprAccess().getGroup_1_0(), "rule__SelectionExpr__Group_1_0__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_0(), "rule__TermExpr__Group_0__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_0_0(), "rule__TermExpr__Group_0_0__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_1(), "rule__TermExpr__Group_1__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_2(), "rule__TermExpr__Group_2__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_3(), "rule__TermExpr__Group_3__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_3_0(), "rule__TermExpr__Group_3_0__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_3_0_0(), "rule__TermExpr__Group_3_0_0__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_3_1(), "rule__TermExpr__Group_3_1__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_3_1_1(), "rule__TermExpr__Group_3_1_1__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_4(), "rule__TermExpr__Group_4__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_4_0(), "rule__TermExpr__Group_4_0__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_4_0_0(), "rule__TermExpr__Group_4_0_0__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_4_2(), "rule__TermExpr__Group_4_2__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_5(), "rule__TermExpr__Group_5__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_5_0(), "rule__TermExpr__Group_5_0__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_5_0_0(), "rule__TermExpr__Group_5_0_0__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_7(), "rule__TermExpr__Group_7__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_8(), "rule__TermExpr__Group_8__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_9(), "rule__TermExpr__Group_9__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_10(), "rule__TermExpr__Group_10__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_11(), "rule__TermExpr__Group_11__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_12(), "rule__TermExpr__Group_12__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_13(), "rule__TermExpr__Group_13__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_14(), "rule__TermExpr__Group_14__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_15(), "rule__TermExpr__Group_15__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_16(), "rule__TermExpr__Group_16__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_17(), "rule__TermExpr__Group_17__0");
			builder.put(grammarAccess.getTermExprAccess().getGroup_18(), "rule__TermExpr__Group_18__0");
			builder.put(grammarAccess.getArrayLiteralExprAccess().getGroup(), "rule__ArrayLiteralExpr__Group__0");
			builder.put(grammarAccess.getArrayLiteralExprAccess().getGroup_1(), "rule__ArrayLiteralExpr__Group_1__0");
			builder.put(grammarAccess.getArrayLiteralExprAccess().getGroup_1_0(), "rule__ArrayLiteralExpr__Group_1_0__0");
			builder.put(grammarAccess.getArrayLiteralExprAccess().getGroup_1_0_1(), "rule__ArrayLiteralExpr__Group_1_0_1__0");
			builder.put(grammarAccess.getArrayLiteralExprAccess().getGroup_1_0_1_1(), "rule__ArrayLiteralExpr__Group_1_0_1_1__0");
			builder.put(grammarAccess.getQCPREFAccess().getGroup(), "rule__QCPREF__Group__0");
			builder.put(grammarAccess.getQCPREFAccess().getGroup_0(), "rule__QCPREF__Group_0__0");
			builder.put(grammarAccess.getQCPREFAccess().getGroup_2(), "rule__QCPREF__Group_2__0");
			builder.put(grammarAccess.getDCIDAccess().getGroup(), "rule__DCID__Group__0");
			builder.put(grammarAccess.getDCIDAccess().getGroup_0(), "rule__DCID__Group_0__0");
			builder.put(grammarAccess.getJavaQualifiedNameAccess().getGroup(), "rule__JavaQualifiedName__Group__0");
			builder.put(grammarAccess.getJavaQualifiedNameAccess().getGroup_1(), "rule__JavaQualifiedName__Group_1__0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getGroup(), "rule__ContainedPropertyAssociation__Group__0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getGroup_3(), "rule__ContainedPropertyAssociation__Group_3__0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getGroup_3_1(), "rule__ContainedPropertyAssociation__Group_3_1__0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getGroup_4(), "rule__ContainedPropertyAssociation__Group_4__0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getGroup_4_2(), "rule__ContainedPropertyAssociation__Group_4_2__0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getGroup_5(), "rule__ContainedPropertyAssociation__Group_5__0");
			builder.put(grammarAccess.getPropertyAssociationAccess().getGroup(), "rule__PropertyAssociation__Group__0");
			builder.put(grammarAccess.getPropertyAssociationAccess().getGroup_3(), "rule__PropertyAssociation__Group_3__0");
			builder.put(grammarAccess.getPropertyAssociationAccess().getGroup_3_1(), "rule__PropertyAssociation__Group_3_1__0");
			builder.put(grammarAccess.getPropertyAssociationAccess().getGroup_4(), "rule__PropertyAssociation__Group_4__0");
			builder.put(grammarAccess.getBasicPropertyAssociationAccess().getGroup(), "rule__BasicPropertyAssociation__Group__0");
			builder.put(grammarAccess.getModalPropertyValueAccess().getGroup(), "rule__ModalPropertyValue__Group__0");
			builder.put(grammarAccess.getModalPropertyValueAccess().getGroup_4(), "rule__ModalPropertyValue__Group_4__0");
			builder.put(grammarAccess.getOptionalModalPropertyValueAccess().getGroup(), "rule__OptionalModalPropertyValue__Group__0");
			builder.put(grammarAccess.getOptionalModalPropertyValueAccess().getGroup_1(), "rule__OptionalModalPropertyValue__Group_1__0");
			builder.put(grammarAccess.getOptionalModalPropertyValueAccess().getGroup_1_3(), "rule__OptionalModalPropertyValue__Group_1_3__0");
			builder.put(grammarAccess.getBooleanLiteralAccess().getGroup(), "rule__BooleanLiteral__Group__0");
			builder.put(grammarAccess.getReferenceTermAccess().getGroup(), "rule__ReferenceTerm__Group__0");
			builder.put(grammarAccess.getRecordTermAccess().getGroup(), "rule__RecordTerm__Group__0");
			builder.put(grammarAccess.getOldRecordTermAccess().getGroup(), "rule__OldRecordTerm__Group__0");
			builder.put(grammarAccess.getComputedTermAccess().getGroup(), "rule__ComputedTerm__Group__0");
			builder.put(grammarAccess.getComponentClassifierTermAccess().getGroup(), "rule__ComponentClassifierTerm__Group__0");
			builder.put(grammarAccess.getListTermAccess().getGroup(), "rule__ListTerm__Group__0");
			builder.put(grammarAccess.getListTermAccess().getGroup_2(), "rule__ListTerm__Group_2__0");
			builder.put(grammarAccess.getListTermAccess().getGroup_2_1(), "rule__ListTerm__Group_2_1__0");
			builder.put(grammarAccess.getFieldPropertyAssociationAccess().getGroup(), "rule__FieldPropertyAssociation__Group__0");
			builder.put(grammarAccess.getContainmentPathElementAccess().getGroup(), "rule__ContainmentPathElement__Group__0");
			builder.put(grammarAccess.getContainmentPathElementAccess().getGroup_0(), "rule__ContainmentPathElement__Group_0__0");
			builder.put(grammarAccess.getContainmentPathElementAccess().getGroup_1(), "rule__ContainmentPathElement__Group_1__0");
			builder.put(grammarAccess.getANNEXREFAccess().getGroup(), "rule__ANNEXREF__Group__0");
			builder.put(grammarAccess.getArrayRangeAccess().getGroup(), "rule__ArrayRange__Group__0");
			builder.put(grammarAccess.getArrayRangeAccess().getGroup_3(), "rule__ArrayRange__Group_3__0");
			builder.put(grammarAccess.getSignedConstantAccess().getGroup(), "rule__SignedConstant__Group__0");
			builder.put(grammarAccess.getIntegerTermAccess().getGroup(), "rule__IntegerTerm__Group__0");
			builder.put(grammarAccess.getSignedIntAccess().getGroup(), "rule__SignedInt__Group__0");
			builder.put(grammarAccess.getRealTermAccess().getGroup(), "rule__RealTerm__Group__0");
			builder.put(grammarAccess.getSignedRealAccess().getGroup(), "rule__SignedReal__Group__0");
			builder.put(grammarAccess.getNumericRangeTermAccess().getGroup(), "rule__NumericRangeTerm__Group__0");
			builder.put(grammarAccess.getNumericRangeTermAccess().getGroup_3(), "rule__NumericRangeTerm__Group_3__0");
			builder.put(grammarAccess.getAppliesToKeywordsAccess().getGroup(), "rule__AppliesToKeywords__Group__0");
			builder.put(grammarAccess.getInBindingKeywordsAccess().getGroup(), "rule__InBindingKeywords__Group__0");
			builder.put(grammarAccess.getInModesKeywordsAccess().getGroup(), "rule__InModesKeywords__Group__0");
			builder.put(grammarAccess.getQCLREFAccess().getGroup(), "rule__QCLREF__Group__0");
			builder.put(grammarAccess.getQPREFAccess().getGroup(), "rule__QPREF__Group__0");
			builder.put(grammarAccess.getQPREFAccess().getGroup_1(), "rule__QPREF__Group_1__0");
			builder.put(grammarAccess.getQCREFAccess().getGroup(), "rule__QCREF__Group__0");
			builder.put(grammarAccess.getQCREFAccess().getGroup_0(), "rule__QCREF__Group_0__0");
			builder.put(grammarAccess.getQCREFAccess().getGroup_2(), "rule__QCREF__Group_2__0");
			builder.put(grammarAccess.getAgreeLibraryAccess().getContractAssignment_1(), "rule__AgreeLibrary__ContractAssignment_1");
			builder.put(grammarAccess.getAgreeSubclauseAccess().getContractAssignment_1(), "rule__AgreeSubclause__ContractAssignment_1");
			builder.put(grammarAccess.getAgreeContractAccess().getSpecsAssignment_1(), "rule__AgreeContract__SpecsAssignment_1");
			builder.put(grammarAccess.getSpecStatementAccess().getExprAssignment_1_3(), "rule__SpecStatement__ExprAssignment_1_3");
			builder.put(grammarAccess.getSpecStatementAccess().getExprAssignment_2_2(), "rule__SpecStatement__ExprAssignment_2_2");
			builder.put(grammarAccess.getSpecStatementAccess().getTypeAssignment_2_4(), "rule__SpecStatement__TypeAssignment_2_4");
			builder.put(grammarAccess.getSpecStatementAccess().getConnAssignment_4_2(), "rule__SpecStatement__ConnAssignment_4_2");
			builder.put(grammarAccess.getSpecStatementAccess().getExprAssignment_4_4(), "rule__SpecStatement__ExprAssignment_4_4");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getNameAssignment_0_2(), "rule__NamedSpecStatement__NameAssignment_0_2");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getStrAssignment_0_3(), "rule__NamedSpecStatement__StrAssignment_0_3");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getExprAssignment_0_5_0(), "rule__NamedSpecStatement__ExprAssignment_0_5_0");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getPatternAssignment_0_5_1(), "rule__NamedSpecStatement__PatternAssignment_0_5_1");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getNameAssignment_1_2(), "rule__NamedSpecStatement__NameAssignment_1_2");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getStrAssignment_1_3(), "rule__NamedSpecStatement__StrAssignment_1_3");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getExprAssignment_1_5_0(), "rule__NamedSpecStatement__ExprAssignment_1_5_0");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getPatternAssignment_1_5_1(), "rule__NamedSpecStatement__PatternAssignment_1_5_1");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getNameAssignment_2_2_0(), "rule__NamedSpecStatement__NameAssignment_2_2_0");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getStrAssignment_2_2_1(), "rule__NamedSpecStatement__StrAssignment_2_2_1");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getExprAssignment_2_3_0(), "rule__NamedSpecStatement__ExprAssignment_2_3_0");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getPatternAssignment_2_3_1(), "rule__NamedSpecStatement__PatternAssignment_2_3_1");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getNameAssignment_3_2(), "rule__NamedSpecStatement__NameAssignment_3_2");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getStrAssignment_3_3(), "rule__NamedSpecStatement__StrAssignment_3_3");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getExprAssignment_3_5_0(), "rule__NamedSpecStatement__ExprAssignment_3_5_0");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getPatternAssignment_3_5_1(), "rule__NamedSpecStatement__PatternAssignment_3_5_1");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getNameAssignment_4_2(), "rule__NamedSpecStatement__NameAssignment_4_2");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getStrAssignment_4_3(), "rule__NamedSpecStatement__StrAssignment_4_3");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getExprAssignment_4_5_0(), "rule__NamedSpecStatement__ExprAssignment_4_5_0");
			builder.put(grammarAccess.getNamedSpecStatementAccess().getPatternAssignment_4_5_1(), "rule__NamedSpecStatement__PatternAssignment_4_5_1");
			builder.put(grammarAccess.getPatternStatementAccess().getExprAssignment_1_2(), "rule__PatternStatement__ExprAssignment_1_2");
			builder.put(grammarAccess.getWhenStatementAccess().getConditionAssignment_0_0_0_2(), "rule__WhenStatement__ConditionAssignment_0_0_0_2");
			builder.put(grammarAccess.getWhenStatementAccess().getConditionIntervalAssignment_0_2(), "rule__WhenStatement__ConditionIntervalAssignment_0_2");
			builder.put(grammarAccess.getWhenStatementAccess().getEventAssignment_0_3(), "rule__WhenStatement__EventAssignment_0_3");
			builder.put(grammarAccess.getWhenStatementAccess().getExclAssignment_0_4(), "rule__WhenStatement__ExclAssignment_0_4");
			builder.put(grammarAccess.getWhenStatementAccess().getEventIntervalAssignment_0_6_1(), "rule__WhenStatement__EventIntervalAssignment_0_6_1");
			builder.put(grammarAccess.getWhenStatementAccess().getConditionAssignment_1_0_0_2(), "rule__WhenStatement__ConditionAssignment_1_0_0_2");
			builder.put(grammarAccess.getWhenStatementAccess().getTimesAssignment_1_1(), "rule__WhenStatement__TimesAssignment_1_1");
			builder.put(grammarAccess.getWhenStatementAccess().getIntervalAssignment_1_4(), "rule__WhenStatement__IntervalAssignment_1_4");
			builder.put(grammarAccess.getWhenStatementAccess().getExclAssignment_1_5(), "rule__WhenStatement__ExclAssignment_1_5");
			builder.put(grammarAccess.getWhenStatementAccess().getEventAssignment_1_7(), "rule__WhenStatement__EventAssignment_1_7");
			builder.put(grammarAccess.getWheneverStatementAccess().getCauseAssignment_0_0_0_2(), "rule__WheneverStatement__CauseAssignment_0_0_0_2");
			builder.put(grammarAccess.getWheneverStatementAccess().getEffectAssignment_0_0_0_4(), "rule__WheneverStatement__EffectAssignment_0_0_0_4");
			builder.put(grammarAccess.getWheneverStatementAccess().getExclAssignment_0_0_0_5(), "rule__WheneverStatement__ExclAssignment_0_0_0_5");
			builder.put(grammarAccess.getWheneverStatementAccess().getIntervalAssignment_0_1_1(), "rule__WheneverStatement__IntervalAssignment_0_1_1");
			builder.put(grammarAccess.getWheneverStatementAccess().getCauseAssignment_1_0_0_2(), "rule__WheneverStatement__CauseAssignment_1_0_0_2");
			builder.put(grammarAccess.getWheneverStatementAccess().getEffectAssignment_1_0_0_5(), "rule__WheneverStatement__EffectAssignment_1_0_0_5");
			builder.put(grammarAccess.getWheneverStatementAccess().getExclAssignment_1_0_0_6(), "rule__WheneverStatement__ExclAssignment_1_0_0_6");
			builder.put(grammarAccess.getWheneverStatementAccess().getIntervalAssignment_1_1_1(), "rule__WheneverStatement__IntervalAssignment_1_1_1");
			builder.put(grammarAccess.getWheneverStatementAccess().getCauseAssignment_2_0_0_2(), "rule__WheneverStatement__CauseAssignment_2_0_0_2");
			builder.put(grammarAccess.getWheneverStatementAccess().getEffectAssignment_2_0_0_4(), "rule__WheneverStatement__EffectAssignment_2_0_0_4");
			builder.put(grammarAccess.getWheneverStatementAccess().getExclAssignment_2_0_0_5(), "rule__WheneverStatement__ExclAssignment_2_0_0_5");
			builder.put(grammarAccess.getWheneverStatementAccess().getIntervalAssignment_2_1_1(), "rule__WheneverStatement__IntervalAssignment_2_1_1");
			builder.put(grammarAccess.getWheneverStatementAccess().getCauseAssignment_3_0_0_2(), "rule__WheneverStatement__CauseAssignment_3_0_0_2");
			builder.put(grammarAccess.getWheneverStatementAccess().getLhsAssignment_3_0_0_4(), "rule__WheneverStatement__LhsAssignment_3_0_0_4");
			builder.put(grammarAccess.getWheneverStatementAccess().getRhsAssignment_3_1(), "rule__WheneverStatement__RhsAssignment_3_1");
			builder.put(grammarAccess.getWheneverStatementAccess().getExclAssignment_3_2(), "rule__WheneverStatement__ExclAssignment_3_2");
			builder.put(grammarAccess.getWheneverStatementAccess().getIntervalAssignment_3_3_1(), "rule__WheneverStatement__IntervalAssignment_3_3_1");
			builder.put(grammarAccess.getRealTimeStatementAccess().getEventAssignment_0_0_0_2(), "rule__RealTimeStatement__EventAssignment_0_0_0_2");
			builder.put(grammarAccess.getRealTimeStatementAccess().getPeriodAssignment_0_1(), "rule__RealTimeStatement__PeriodAssignment_0_1");
			builder.put(grammarAccess.getRealTimeStatementAccess().getJitterAssignment_0_2_2(), "rule__RealTimeStatement__JitterAssignment_0_2_2");
			builder.put(grammarAccess.getRealTimeStatementAccess().getEventAssignment_1_0_0_2(), "rule__RealTimeStatement__EventAssignment_1_0_0_2");
			builder.put(grammarAccess.getRealTimeStatementAccess().getIatAssignment_1_3(), "rule__RealTimeStatement__IatAssignment_1_3");
			builder.put(grammarAccess.getRealTimeStatementAccess().getJitterAssignment_1_4_2(), "rule__RealTimeStatement__JitterAssignment_1_4_2");
			builder.put(grammarAccess.getTimeIntervalAccess().getLowAssignment_0_0_2(), "rule__TimeInterval__LowAssignment_0_0_2");
			builder.put(grammarAccess.getTimeIntervalAccess().getHighAssignment_0_0_4(), "rule__TimeInterval__HighAssignment_0_0_4");
			builder.put(grammarAccess.getTimeIntervalAccess().getLowAssignment_1_0_2(), "rule__TimeInterval__LowAssignment_1_0_2");
			builder.put(grammarAccess.getTimeIntervalAccess().getHighAssignment_1_0_4(), "rule__TimeInterval__HighAssignment_1_0_4");
			builder.put(grammarAccess.getTimeIntervalAccess().getLowAssignment_2_0_2(), "rule__TimeInterval__LowAssignment_2_0_2");
			builder.put(grammarAccess.getTimeIntervalAccess().getHighAssignment_2_0_4(), "rule__TimeInterval__HighAssignment_2_0_4");
			builder.put(grammarAccess.getTimeIntervalAccess().getLowAssignment_3_0_2(), "rule__TimeInterval__LowAssignment_3_0_2");
			builder.put(grammarAccess.getTimeIntervalAccess().getHighAssignment_3_0_4(), "rule__TimeInterval__HighAssignment_3_0_4");
			builder.put(grammarAccess.getSynchStatementAccess().getValAssignment_0_3(), "rule__SynchStatement__ValAssignment_0_3");
			builder.put(grammarAccess.getSynchStatementAccess().getVal2Assignment_0_4_1(), "rule__SynchStatement__Val2Assignment_0_4_1");
			builder.put(grammarAccess.getSynchStatementAccess().getSimAssignment_0_5(), "rule__SynchStatement__SimAssignment_0_5");
			builder.put(grammarAccess.getSynchStatementAccess().getComp1Assignment_1_3_0(), "rule__SynchStatement__Comp1Assignment_1_3_0");
			builder.put(grammarAccess.getSynchStatementAccess().getComp2Assignment_1_3_2(), "rule__SynchStatement__Comp2Assignment_1_3_2");
			builder.put(grammarAccess.getSynchStatementAccess().getMaxAssignment_1_3_4(), "rule__SynchStatement__MaxAssignment_1_3_4");
			builder.put(grammarAccess.getSynchStatementAccess().getMinAssignment_1_3_6(), "rule__SynchStatement__MinAssignment_1_3_6");
			builder.put(grammarAccess.getSynchStatementAccess().getElsAssignment_2_3(), "rule__SynchStatement__ElsAssignment_2_3");
			builder.put(grammarAccess.getSynchStatementAccess().getElsAssignment_2_4_1(), "rule__SynchStatement__ElsAssignment_2_4_1");
			builder.put(grammarAccess.getOrderStatementAccess().getCompsAssignment_2(), "rule__OrderStatement__CompsAssignment_2");
			builder.put(grammarAccess.getOrderStatementAccess().getCompsAssignment_3_1(), "rule__OrderStatement__CompsAssignment_3_1");
			builder.put(grammarAccess.getPropertyStatementAccess().getNameAssignment_1(), "rule__PropertyStatement__NameAssignment_1");
			builder.put(grammarAccess.getPropertyStatementAccess().getExprAssignment_3(), "rule__PropertyStatement__ExprAssignment_3");
			builder.put(grammarAccess.getConstStatementAccess().getNameAssignment_1(), "rule__ConstStatement__NameAssignment_1");
			builder.put(grammarAccess.getConstStatementAccess().getTypeAssignment_3(), "rule__ConstStatement__TypeAssignment_3");
			builder.put(grammarAccess.getConstStatementAccess().getExprAssignment_5(), "rule__ConstStatement__ExprAssignment_5");
			builder.put(grammarAccess.getEqStatementAccess().getLhsAssignment_1_0(), "rule__EqStatement__LhsAssignment_1_0");
			builder.put(grammarAccess.getEqStatementAccess().getLhsAssignment_1_1_1(), "rule__EqStatement__LhsAssignment_1_1_1");
			builder.put(grammarAccess.getEqStatementAccess().getExprAssignment_2_1(), "rule__EqStatement__ExprAssignment_2_1");
			builder.put(grammarAccess.getInputStatementAccess().getLhsAssignment_1_0(), "rule__InputStatement__LhsAssignment_1_0");
			builder.put(grammarAccess.getInputStatementAccess().getLhsAssignment_1_1_1(), "rule__InputStatement__LhsAssignment_1_1_1");
			builder.put(grammarAccess.getAssignStatementAccess().getIdAssignment_1(), "rule__AssignStatement__IdAssignment_1");
			builder.put(grammarAccess.getAssignStatementAccess().getExprAssignment_3(), "rule__AssignStatement__ExprAssignment_3");
			builder.put(grammarAccess.getFnDefAccess().getNameAssignment_1(), "rule__FnDef__NameAssignment_1");
			builder.put(grammarAccess.getFnDefAccess().getArgsAssignment_3(), "rule__FnDef__ArgsAssignment_3");
			builder.put(grammarAccess.getFnDefAccess().getArgsAssignment_4_1(), "rule__FnDef__ArgsAssignment_4_1");
			builder.put(grammarAccess.getFnDefAccess().getTypeAssignment_7(), "rule__FnDef__TypeAssignment_7");
			builder.put(grammarAccess.getFnDefAccess().getExprAssignment_9(), "rule__FnDef__ExprAssignment_9");
			builder.put(grammarAccess.getLibraryFnDefAccess().getNameAssignment_1(), "rule__LibraryFnDef__NameAssignment_1");
			builder.put(grammarAccess.getLibraryFnDefAccess().getArgsAssignment_3(), "rule__LibraryFnDef__ArgsAssignment_3");
			builder.put(grammarAccess.getLibraryFnDefAccess().getArgsAssignment_4_1(), "rule__LibraryFnDef__ArgsAssignment_4_1");
			builder.put(grammarAccess.getLibraryFnDefAccess().getTypeAssignment_7(), "rule__LibraryFnDef__TypeAssignment_7");
			builder.put(grammarAccess.getUninterpretedFnDefAccess().getNameAssignment_1(), "rule__UninterpretedFnDef__NameAssignment_1");
			builder.put(grammarAccess.getUninterpretedFnDefAccess().getArgsAssignment_3(), "rule__UninterpretedFnDef__ArgsAssignment_3");
			builder.put(grammarAccess.getUninterpretedFnDefAccess().getArgsAssignment_4_1(), "rule__UninterpretedFnDef__ArgsAssignment_4_1");
			builder.put(grammarAccess.getUninterpretedFnDefAccess().getTypeAssignment_7(), "rule__UninterpretedFnDef__TypeAssignment_7");
			builder.put(grammarAccess.getLinearizationDefAccess().getNameAssignment_1(), "rule__LinearizationDef__NameAssignment_1");
			builder.put(grammarAccess.getLinearizationDefAccess().getArgsAssignment_3(), "rule__LinearizationDef__ArgsAssignment_3");
			builder.put(grammarAccess.getLinearizationDefAccess().getArgsAssignment_4_1(), "rule__LinearizationDef__ArgsAssignment_4_1");
			builder.put(grammarAccess.getLinearizationDefAccess().getIntervalsAssignment_8(), "rule__LinearizationDef__IntervalsAssignment_8");
			builder.put(grammarAccess.getLinearizationDefAccess().getIntervalsAssignment_9_1(), "rule__LinearizationDef__IntervalsAssignment_9_1");
			builder.put(grammarAccess.getLinearizationDefAccess().getPrecisionAssignment_11_1(), "rule__LinearizationDef__PrecisionAssignment_11_1");
			builder.put(grammarAccess.getLinearizationDefAccess().getExprBodyAssignment_13(), "rule__LinearizationDef__ExprBodyAssignment_13");
			builder.put(grammarAccess.getLinearizationIntervalAccess().getStartAssignment_0(), "rule__LinearizationInterval__StartAssignment_0");
			builder.put(grammarAccess.getLinearizationIntervalAccess().getEndAssignment_2(), "rule__LinearizationInterval__EndAssignment_2");
			builder.put(grammarAccess.getNodeDefAccess().getNameAssignment_1(), "rule__NodeDef__NameAssignment_1");
			builder.put(grammarAccess.getNodeDefAccess().getArgsAssignment_3_0(), "rule__NodeDef__ArgsAssignment_3_0");
			builder.put(grammarAccess.getNodeDefAccess().getArgsAssignment_3_1_1(), "rule__NodeDef__ArgsAssignment_3_1_1");
			builder.put(grammarAccess.getNodeDefAccess().getRetsAssignment_7_0(), "rule__NodeDef__RetsAssignment_7_0");
			builder.put(grammarAccess.getNodeDefAccess().getRetsAssignment_7_1_1(), "rule__NodeDef__RetsAssignment_7_1_1");
			builder.put(grammarAccess.getNodeDefAccess().getNodeBodyAssignment_10(), "rule__NodeDef__NodeBodyAssignment_10");
			builder.put(grammarAccess.getNodeBodyExprAccess().getLocsAssignment_0_1_0(), "rule__NodeBodyExpr__LocsAssignment_0_1_0");
			builder.put(grammarAccess.getNodeBodyExprAccess().getStmtsAssignment_2(), "rule__NodeBodyExpr__StmtsAssignment_2");
			builder.put(grammarAccess.getNodeStmtAccess().getLhsAssignment_0_1(), "rule__NodeStmt__LhsAssignment_0_1");
			builder.put(grammarAccess.getNodeStmtAccess().getLhsAssignment_0_2_1(), "rule__NodeStmt__LhsAssignment_0_2_1");
			builder.put(grammarAccess.getNodeStmtAccess().getExprAssignment_0_4(), "rule__NodeStmt__ExprAssignment_0_4");
			builder.put(grammarAccess.getNodeStmtAccess().getStrAssignment_1_2(), "rule__NodeStmt__StrAssignment_1_2");
			builder.put(grammarAccess.getNodeStmtAccess().getExprAssignment_1_4(), "rule__NodeStmt__ExprAssignment_1_4");
			builder.put(grammarAccess.getArgAccess().getNameAssignment_0_0(), "rule__Arg__NameAssignment_0_0");
			builder.put(grammarAccess.getArgAccess().getTypeAssignment_0_2(), "rule__Arg__TypeAssignment_0_2");
			builder.put(grammarAccess.getTypeAccess().getSizeAssignment_1_0_2(), "rule__Type__SizeAssignment_1_0_2");
			builder.put(grammarAccess.getBaseTypeAccess().getNameAssignment_0_1(), "rule__BaseType__NameAssignment_0_1");
			builder.put(grammarAccess.getBaseTypeAccess().getLowNegAssignment_0_2_1(), "rule__BaseType__LowNegAssignment_0_2_1");
			builder.put(grammarAccess.getBaseTypeAccess().getRangeLowAssignment_0_2_2(), "rule__BaseType__RangeLowAssignment_0_2_2");
			builder.put(grammarAccess.getBaseTypeAccess().getHighNegAssignment_0_2_4(), "rule__BaseType__HighNegAssignment_0_2_4");
			builder.put(grammarAccess.getBaseTypeAccess().getRangeHighAssignment_0_2_5(), "rule__BaseType__RangeHighAssignment_0_2_5");
			builder.put(grammarAccess.getRecordDefAccess().getNameAssignment_1(), "rule__RecordDef__NameAssignment_1");
			builder.put(grammarAccess.getRecordDefAccess().getArgsAssignment_5_0(), "rule__RecordDef__ArgsAssignment_5_0");
			builder.put(grammarAccess.getRecordDefAccess().getArgsAssignment_5_1_1(), "rule__RecordDef__ArgsAssignment_5_1_1");
			builder.put(grammarAccess.getEnumStatementAccess().getNameAssignment_1(), "rule__EnumStatement__NameAssignment_1");
			builder.put(grammarAccess.getEnumStatementAccess().getEnumsAssignment_4(), "rule__EnumStatement__EnumsAssignment_4");
			builder.put(grammarAccess.getEnumStatementAccess().getEnumsAssignment_5_1(), "rule__EnumStatement__EnumsAssignment_5_1");
			builder.put(grammarAccess.getForallExprAccess().getBindingAssignment_0_2(), "rule__ForallExpr__BindingAssignment_0_2");
			builder.put(grammarAccess.getForallExprAccess().getArrayAssignment_0_4(), "rule__ForallExpr__ArrayAssignment_0_4");
			builder.put(grammarAccess.getForallExprAccess().getExprAssignment_0_6(), "rule__ForallExpr__ExprAssignment_0_6");
			builder.put(grammarAccess.getExistsExprAccess().getBindingAssignment_0_2(), "rule__ExistsExpr__BindingAssignment_0_2");
			builder.put(grammarAccess.getExistsExprAccess().getArrayAssignment_0_4(), "rule__ExistsExpr__ArrayAssignment_0_4");
			builder.put(grammarAccess.getExistsExprAccess().getExprAssignment_0_6(), "rule__ExistsExpr__ExprAssignment_0_6");
			builder.put(grammarAccess.getFlatmapExprAccess().getBindingAssignment_0_2(), "rule__FlatmapExpr__BindingAssignment_0_2");
			builder.put(grammarAccess.getFlatmapExprAccess().getArrayAssignment_0_4(), "rule__FlatmapExpr__ArrayAssignment_0_4");
			builder.put(grammarAccess.getFlatmapExprAccess().getExprAssignment_0_6(), "rule__FlatmapExpr__ExprAssignment_0_6");
			builder.put(grammarAccess.getFoldLeftExprAccess().getBindingAssignment_0_2(), "rule__FoldLeftExpr__BindingAssignment_0_2");
			builder.put(grammarAccess.getFoldLeftExprAccess().getArrayAssignment_0_4(), "rule__FoldLeftExpr__ArrayAssignment_0_4");
			builder.put(grammarAccess.getFoldLeftExprAccess().getAccumulatorAssignment_0_6(), "rule__FoldLeftExpr__AccumulatorAssignment_0_6");
			builder.put(grammarAccess.getFoldLeftExprAccess().getInitialAssignment_0_8(), "rule__FoldLeftExpr__InitialAssignment_0_8");
			builder.put(grammarAccess.getFoldLeftExprAccess().getExprAssignment_0_10(), "rule__FoldLeftExpr__ExprAssignment_0_10");
			builder.put(grammarAccess.getFoldRightExprAccess().getBindingAssignment_0_2(), "rule__FoldRightExpr__BindingAssignment_0_2");
			builder.put(grammarAccess.getFoldRightExprAccess().getArrayAssignment_0_4(), "rule__FoldRightExpr__ArrayAssignment_0_4");
			builder.put(grammarAccess.getFoldRightExprAccess().getAccumulatorAssignment_0_6(), "rule__FoldRightExpr__AccumulatorAssignment_0_6");
			builder.put(grammarAccess.getFoldRightExprAccess().getInitialAssignment_0_8(), "rule__FoldRightExpr__InitialAssignment_0_8");
			builder.put(grammarAccess.getFoldRightExprAccess().getExprAssignment_0_10(), "rule__FoldRightExpr__ExprAssignment_0_10");
			builder.put(grammarAccess.getArrowExprAccess().getOpAssignment_1_0_0_1(), "rule__ArrowExpr__OpAssignment_1_0_0_1");
			builder.put(grammarAccess.getArrowExprAccess().getRightAssignment_1_1(), "rule__ArrowExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getImpliesExprAccess().getOpAssignment_1_0_0_1(), "rule__ImpliesExpr__OpAssignment_1_0_0_1");
			builder.put(grammarAccess.getImpliesExprAccess().getRightAssignment_1_1(), "rule__ImpliesExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getEquivExprAccess().getOpAssignment_1_0_0_1(), "rule__EquivExpr__OpAssignment_1_0_0_1");
			builder.put(grammarAccess.getEquivExprAccess().getRightAssignment_1_1(), "rule__EquivExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getOrExprAccess().getOpAssignment_1_0_0_1(), "rule__OrExpr__OpAssignment_1_0_0_1");
			builder.put(grammarAccess.getOrExprAccess().getRightAssignment_1_1(), "rule__OrExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getAndExprAccess().getOpAssignment_1_0_0_1(), "rule__AndExpr__OpAssignment_1_0_0_1");
			builder.put(grammarAccess.getAndExprAccess().getRightAssignment_1_1(), "rule__AndExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getRelateExprAccess().getOpAssignment_1_0_0_1(), "rule__RelateExpr__OpAssignment_1_0_0_1");
			builder.put(grammarAccess.getRelateExprAccess().getRightAssignment_1_1(), "rule__RelateExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getAddSubExprAccess().getOpAssignment_1_0_0_1(), "rule__AddSubExpr__OpAssignment_1_0_0_1");
			builder.put(grammarAccess.getAddSubExprAccess().getRightAssignment_1_1(), "rule__AddSubExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getMultDivExprAccess().getOpAssignment_1_0_0_1(), "rule__MultDivExpr__OpAssignment_1_0_0_1");
			builder.put(grammarAccess.getMultDivExprAccess().getRightAssignment_1_1(), "rule__MultDivExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getPowerExprAccess().getOpAssignment_1_0_0_1(), "rule__PowerExpr__OpAssignment_1_0_0_1");
			builder.put(grammarAccess.getPowerExprAccess().getRightAssignment_1_1(), "rule__PowerExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getUnaryExprAccess().getOpAssignment_0_1(), "rule__UnaryExpr__OpAssignment_0_1");
			builder.put(grammarAccess.getUnaryExprAccess().getExprAssignment_0_2(), "rule__UnaryExpr__ExprAssignment_0_2");
			builder.put(grammarAccess.getIfThenElseExprAccess().getAAssignment_0_2(), "rule__IfThenElseExpr__AAssignment_0_2");
			builder.put(grammarAccess.getIfThenElseExprAccess().getBAssignment_0_4(), "rule__IfThenElseExpr__BAssignment_0_4");
			builder.put(grammarAccess.getIfThenElseExprAccess().getCAssignment_0_6(), "rule__IfThenElseExpr__CAssignment_0_6");
			builder.put(grammarAccess.getPreDefFnExprAccess().getDelayAssignment_0_3(), "rule__PreDefFnExpr__DelayAssignment_0_3");
			builder.put(grammarAccess.getPreDefFnExprAccess().getInitAssignment_0_5(), "rule__PreDefFnExpr__InitAssignment_0_5");
			builder.put(grammarAccess.getPreDefFnExprAccess().getComponentRefAssignment_1_3(), "rule__PreDefFnExpr__ComponentRefAssignment_1_3");
			builder.put(grammarAccess.getPreDefFnExprAccess().getPropAssignment_1_5(), "rule__PreDefFnExpr__PropAssignment_1_5");
			builder.put(grammarAccess.getArrayUpdateExprAccess().getIndicesAssignment_1_0_0_2(), "rule__ArrayUpdateExpr__IndicesAssignment_1_0_0_2");
			builder.put(grammarAccess.getArrayUpdateExprAccess().getValueExprsAssignment_1_1(), "rule__ArrayUpdateExpr__ValueExprsAssignment_1_1");
			builder.put(grammarAccess.getArrayUpdateExprAccess().getIndicesAssignment_1_2_1(), "rule__ArrayUpdateExpr__IndicesAssignment_1_2_1");
			builder.put(grammarAccess.getArrayUpdateExprAccess().getValueExprsAssignment_1_2_3(), "rule__ArrayUpdateExpr__ValueExprsAssignment_1_2_3");
			builder.put(grammarAccess.getRecordUpdateExprAccess().getKeyAssignment_1_0_2(), "rule__RecordUpdateExpr__KeyAssignment_1_0_2");
			builder.put(grammarAccess.getRecordUpdateExprAccess().getExprAssignment_1_0_4(), "rule__RecordUpdateExpr__ExprAssignment_1_0_4");
			builder.put(grammarAccess.getArraySubExprAccess().getIndexAssignment_1_0_2(), "rule__ArraySubExpr__IndexAssignment_1_0_2");
			builder.put(grammarAccess.getTagExprAccess().getTagAssignment_1_2(), "rule__TagExpr__TagAssignment_1_2");
			builder.put(grammarAccess.getSelectionExprAccess().getFieldAssignment_1_0_2(), "rule__SelectionExpr__FieldAssignment_1_0_2");
			builder.put(grammarAccess.getTermExprAccess().getElmAssignment_0_0_1(), "rule__TermExpr__ElmAssignment_0_0_1");
			builder.put(grammarAccess.getTermExprAccess().getArrayAssignment_2_3(), "rule__TermExpr__ArrayAssignment_2_3");
			builder.put(grammarAccess.getTermExprAccess().getRefAssignment_3_0_0_1(), "rule__TermExpr__RefAssignment_3_0_0_1");
			builder.put(grammarAccess.getTermExprAccess().getArgsAssignment_3_1_0(), "rule__TermExpr__ArgsAssignment_3_1_0");
			builder.put(grammarAccess.getTermExprAccess().getArgsAssignment_3_1_1_1(), "rule__TermExpr__ArgsAssignment_3_1_1_1");
			builder.put(grammarAccess.getTermExprAccess().getRecordTypeAssignment_4_0_0_1(), "rule__TermExpr__RecordTypeAssignment_4_0_0_1");
			builder.put(grammarAccess.getTermExprAccess().getArgsAssignment_4_0_0_3(), "rule__TermExpr__ArgsAssignment_4_0_0_3");
			builder.put(grammarAccess.getTermExprAccess().getArgExprAssignment_4_1(), "rule__TermExpr__ArgExprAssignment_4_1");
			builder.put(grammarAccess.getTermExprAccess().getArgsAssignment_4_2_1(), "rule__TermExpr__ArgsAssignment_4_2_1");
			builder.put(grammarAccess.getTermExprAccess().getArgExprAssignment_4_2_3(), "rule__TermExpr__ArgExprAssignment_4_2_3");
			builder.put(grammarAccess.getTermExprAccess().getEnumTypeAssignment_5_1(), "rule__TermExpr__EnumTypeAssignment_5_1");
			builder.put(grammarAccess.getTermExprAccess().getValueAssignment_5_3(), "rule__TermExpr__ValueAssignment_5_3");
			builder.put(grammarAccess.getTermExprAccess().getValAssignment_7_1(), "rule__TermExpr__ValAssignment_7_1");
			builder.put(grammarAccess.getTermExprAccess().getExprAssignment_8_3(), "rule__TermExpr__ExprAssignment_8_3");
			builder.put(grammarAccess.getTermExprAccess().getPortAssignment_9_3(), "rule__TermExpr__PortAssignment_9_3");
			builder.put(grammarAccess.getTermExprAccess().getExprAssignment_10_3(), "rule__TermExpr__ExprAssignment_10_3");
			builder.put(grammarAccess.getTermExprAccess().getIdAssignment_11_3(), "rule__TermExpr__IdAssignment_11_3");
			builder.put(grammarAccess.getTermExprAccess().getIdAssignment_12_3(), "rule__TermExpr__IdAssignment_12_3");
			builder.put(grammarAccess.getTermExprAccess().getIdAssignment_13_3(), "rule__TermExpr__IdAssignment_13_3");
			builder.put(grammarAccess.getTermExprAccess().getValAssignment_14_1(), "rule__TermExpr__ValAssignment_14_1");
			builder.put(grammarAccess.getTermExprAccess().getValAssignment_15_1(), "rule__TermExpr__ValAssignment_15_1");
			builder.put(grammarAccess.getTermExprAccess().getExprAssignment_16_3(), "rule__TermExpr__ExprAssignment_16_3");
			builder.put(grammarAccess.getTermExprAccess().getExprAssignment_17_3(), "rule__TermExpr__ExprAssignment_17_3");
			builder.put(grammarAccess.getArrayLiteralExprAccess().getElemsAssignment_1_0_1_0(), "rule__ArrayLiteralExpr__ElemsAssignment_1_0_1_0");
			builder.put(grammarAccess.getArrayLiteralExprAccess().getElemsAssignment_1_0_1_1_1(), "rule__ArrayLiteralExpr__ElemsAssignment_1_0_1_1_1");
			builder.put(grammarAccess.getDoubleDotRefAccess().getElmAssignment(), "rule__DoubleDotRef__ElmAssignment");
			builder.put(grammarAccess.getNamedIDAccess().getNameAssignment(), "rule__NamedID__NameAssignment");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getPropertyAssignment_0(), "rule__ContainedPropertyAssociation__PropertyAssignment_0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getAppendAssignment_1_1(), "rule__ContainedPropertyAssociation__AppendAssignment_1_1");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getConstantAssignment_2(), "rule__ContainedPropertyAssociation__ConstantAssignment_2");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getOwnedValueAssignment_3_0(), "rule__ContainedPropertyAssociation__OwnedValueAssignment_3_0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getOwnedValueAssignment_3_1_1(), "rule__ContainedPropertyAssociation__OwnedValueAssignment_3_1_1");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getAppliesToAssignment_4_1(), "rule__ContainedPropertyAssociation__AppliesToAssignment_4_1");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getAppliesToAssignment_4_2_1(), "rule__ContainedPropertyAssociation__AppliesToAssignment_4_2_1");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getInBindingAssignment_5_2(), "rule__ContainedPropertyAssociation__InBindingAssignment_5_2");
			builder.put(grammarAccess.getPropertyAssociationAccess().getPropertyAssignment_0(), "rule__PropertyAssociation__PropertyAssignment_0");
			builder.put(grammarAccess.getPropertyAssociationAccess().getAppendAssignment_1_1(), "rule__PropertyAssociation__AppendAssignment_1_1");
			builder.put(grammarAccess.getPropertyAssociationAccess().getConstantAssignment_2(), "rule__PropertyAssociation__ConstantAssignment_2");
			builder.put(grammarAccess.getPropertyAssociationAccess().getOwnedValueAssignment_3_0(), "rule__PropertyAssociation__OwnedValueAssignment_3_0");
			builder.put(grammarAccess.getPropertyAssociationAccess().getOwnedValueAssignment_3_1_1(), "rule__PropertyAssociation__OwnedValueAssignment_3_1_1");
			builder.put(grammarAccess.getPropertyAssociationAccess().getInBindingAssignment_4_2(), "rule__PropertyAssociation__InBindingAssignment_4_2");
			builder.put(grammarAccess.getBasicPropertyAssociationAccess().getPropertyAssignment_0(), "rule__BasicPropertyAssociation__PropertyAssignment_0");
			builder.put(grammarAccess.getBasicPropertyAssociationAccess().getOwnedValueAssignment_2(), "rule__BasicPropertyAssociation__OwnedValueAssignment_2");
			builder.put(grammarAccess.getContainmentPathAccess().getPathAssignment(), "rule__ContainmentPath__PathAssignment");
			builder.put(grammarAccess.getModalPropertyValueAccess().getOwnedValueAssignment_0(), "rule__ModalPropertyValue__OwnedValueAssignment_0");
			builder.put(grammarAccess.getModalPropertyValueAccess().getInModeAssignment_3(), "rule__ModalPropertyValue__InModeAssignment_3");
			builder.put(grammarAccess.getModalPropertyValueAccess().getInModeAssignment_4_1(), "rule__ModalPropertyValue__InModeAssignment_4_1");
			builder.put(grammarAccess.getOptionalModalPropertyValueAccess().getOwnedValueAssignment_0(), "rule__OptionalModalPropertyValue__OwnedValueAssignment_0");
			builder.put(grammarAccess.getOptionalModalPropertyValueAccess().getInModeAssignment_1_2(), "rule__OptionalModalPropertyValue__InModeAssignment_1_2");
			builder.put(grammarAccess.getOptionalModalPropertyValueAccess().getInModeAssignment_1_3_1(), "rule__OptionalModalPropertyValue__InModeAssignment_1_3_1");
			builder.put(grammarAccess.getPropertyValueAccess().getOwnedValueAssignment(), "rule__PropertyValue__OwnedValueAssignment");
			builder.put(grammarAccess.getLiteralorReferenceTermAccess().getNamedValueAssignment(), "rule__LiteralorReferenceTerm__NamedValueAssignment");
			builder.put(grammarAccess.getBooleanLiteralAccess().getValueAssignment_1_0(), "rule__BooleanLiteral__ValueAssignment_1_0");
			builder.put(grammarAccess.getConstantValueAccess().getNamedValueAssignment(), "rule__ConstantValue__NamedValueAssignment");
			builder.put(grammarAccess.getReferenceTermAccess().getPathAssignment_2(), "rule__ReferenceTerm__PathAssignment_2");
			builder.put(grammarAccess.getRecordTermAccess().getOwnedFieldValueAssignment_1(), "rule__RecordTerm__OwnedFieldValueAssignment_1");
			builder.put(grammarAccess.getOldRecordTermAccess().getOwnedFieldValueAssignment_1(), "rule__OldRecordTerm__OwnedFieldValueAssignment_1");
			builder.put(grammarAccess.getComputedTermAccess().getFunctionAssignment_2(), "rule__ComputedTerm__FunctionAssignment_2");
			builder.put(grammarAccess.getComponentClassifierTermAccess().getClassifierAssignment_2(), "rule__ComponentClassifierTerm__ClassifierAssignment_2");
			builder.put(grammarAccess.getListTermAccess().getOwnedListElementAssignment_2_0(), "rule__ListTerm__OwnedListElementAssignment_2_0");
			builder.put(grammarAccess.getListTermAccess().getOwnedListElementAssignment_2_1_1(), "rule__ListTerm__OwnedListElementAssignment_2_1_1");
			builder.put(grammarAccess.getFieldPropertyAssociationAccess().getPropertyAssignment_0(), "rule__FieldPropertyAssociation__PropertyAssignment_0");
			builder.put(grammarAccess.getFieldPropertyAssociationAccess().getOwnedValueAssignment_2(), "rule__FieldPropertyAssociation__OwnedValueAssignment_2");
			builder.put(grammarAccess.getContainmentPathElementAccess().getNamedElementAssignment_0_0(), "rule__ContainmentPathElement__NamedElementAssignment_0_0");
			builder.put(grammarAccess.getContainmentPathElementAccess().getArrayRangeAssignment_0_1(), "rule__ContainmentPathElement__ArrayRangeAssignment_0_1");
			builder.put(grammarAccess.getContainmentPathElementAccess().getPathAssignment_1_1(), "rule__ContainmentPathElement__PathAssignment_1_1");
			builder.put(grammarAccess.getStringTermAccess().getValueAssignment(), "rule__StringTerm__ValueAssignment");
			builder.put(grammarAccess.getArrayRangeAccess().getLowerBoundAssignment_2(), "rule__ArrayRange__LowerBoundAssignment_2");
			builder.put(grammarAccess.getArrayRangeAccess().getUpperBoundAssignment_3_1(), "rule__ArrayRange__UpperBoundAssignment_3_1");
			builder.put(grammarAccess.getSignedConstantAccess().getOpAssignment_0(), "rule__SignedConstant__OpAssignment_0");
			builder.put(grammarAccess.getSignedConstantAccess().getOwnedPropertyExpressionAssignment_1(), "rule__SignedConstant__OwnedPropertyExpressionAssignment_1");
			builder.put(grammarAccess.getIntegerTermAccess().getValueAssignment_0(), "rule__IntegerTerm__ValueAssignment_0");
			builder.put(grammarAccess.getIntegerTermAccess().getUnitAssignment_1(), "rule__IntegerTerm__UnitAssignment_1");
			builder.put(grammarAccess.getRealTermAccess().getValueAssignment_0(), "rule__RealTerm__ValueAssignment_0");
			builder.put(grammarAccess.getRealTermAccess().getUnitAssignment_1(), "rule__RealTerm__UnitAssignment_1");
			builder.put(grammarAccess.getNumericRangeTermAccess().getMinimumAssignment_0(), "rule__NumericRangeTerm__MinimumAssignment_0");
			builder.put(grammarAccess.getNumericRangeTermAccess().getMaximumAssignment_2(), "rule__NumericRangeTerm__MaximumAssignment_2");
			builder.put(grammarAccess.getNumericRangeTermAccess().getDeltaAssignment_3_1(), "rule__NumericRangeTerm__DeltaAssignment_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private AgreeGrammarAccess grammarAccess;

	@Override
	protected InternalAgreeParser createParser() {
		InternalAgreeParser result = new InternalAgreeParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_SL_COMMENT" };
	}

	public AgreeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AgreeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
