/**
 * Copyright (c) 2022, Collins Aerospace.
 * Developed with the sponsorship of Defense Advanced Research Projects Agency (DARPA).
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this data, 
 * including any software or models in source or binary form, as well as any drawings, specifications, 
 * and documentation (collectively "the Data"), to deal in the Data without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Data, and to permit persons to whom the Data is furnished to do so, 
 * subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Data.
 * 
 * THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
 * LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 * IN NO EVENT SHALL THE AUTHORS, SPONSORS, DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE LIABLE 
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE DATA.
 * 
 * Generated by Xtext version 2.25.0.
 */
package com.rockwellcollins.atc.agree.agree;

import org.eclipse.emf.common.util.EList;

import org.osate.aadl2.NamedElement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MN Synch Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.rockwellcollins.atc.agree.agree.MNSynchStatement#getComp1 <em>Comp1</em>}</li>
 *   <li>{@link com.rockwellcollins.atc.agree.agree.MNSynchStatement#getComp2 <em>Comp2</em>}</li>
 *   <li>{@link com.rockwellcollins.atc.agree.agree.MNSynchStatement#getMax <em>Max</em>}</li>
 *   <li>{@link com.rockwellcollins.atc.agree.agree.MNSynchStatement#getMin <em>Min</em>}</li>
 * </ul>
 *
 * @see com.rockwellcollins.atc.agree.agree.AgreePackage#getMNSynchStatement()
 * @model
 * @generated
 */
public interface MNSynchStatement extends SynchStatement
{
  /**
   * Returns the value of the '<em><b>Comp1</b></em>' reference list.
   * The list contents are of type {@link org.osate.aadl2.NamedElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comp1</em>' reference list.
   * @see com.rockwellcollins.atc.agree.agree.AgreePackage#getMNSynchStatement_Comp1()
   * @model
   * @generated
   */
  EList<NamedElement> getComp1();

  /**
   * Returns the value of the '<em><b>Comp2</b></em>' reference list.
   * The list contents are of type {@link org.osate.aadl2.NamedElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comp2</em>' reference list.
   * @see com.rockwellcollins.atc.agree.agree.AgreePackage#getMNSynchStatement_Comp2()
   * @model
   * @generated
   */
  EList<NamedElement> getComp2();

  /**
   * Returns the value of the '<em><b>Max</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max</em>' attribute list.
   * @see com.rockwellcollins.atc.agree.agree.AgreePackage#getMNSynchStatement_Max()
   * @model unique="false"
   * @generated
   */
  EList<String> getMax();

  /**
   * Returns the value of the '<em><b>Min</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min</em>' attribute list.
   * @see com.rockwellcollins.atc.agree.agree.AgreePackage#getMNSynchStatement_Min()
   * @model unique="false"
   * @generated
   */
  EList<String> getMin();

} // MNSynchStatement
