/**
 * Copyright (c) 2021, Collins Aerospace.
 * Developed with the sponsorship of Defense Advanced Research Projects Agency (DARPA).
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this data, 
 * including any software or models in source or binary form, as well as any drawings, specifications, 
 * and documentation (collectively "the Data"), to deal in the Data without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Data, and to permit persons to whom the Data is furnished to do so, 
 * subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Data.
 * 
 * THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
 * LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 * IN NO EVENT SHALL THE AUTHORS, SPONSORS, DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE LIABLE 
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE DATA.
 * 
 * Generated by Xtext version 2.25.0.
 */
package com.rockwellcollins.atc.agree.agree;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prim Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.rockwellcollins.atc.agree.agree.PrimType#getName <em>Name</em>}</li>
 *   <li>{@link com.rockwellcollins.atc.agree.agree.PrimType#getLowNeg <em>Low Neg</em>}</li>
 *   <li>{@link com.rockwellcollins.atc.agree.agree.PrimType#getRangeLow <em>Range Low</em>}</li>
 *   <li>{@link com.rockwellcollins.atc.agree.agree.PrimType#getHighNeg <em>High Neg</em>}</li>
 *   <li>{@link com.rockwellcollins.atc.agree.agree.PrimType#getRangeHigh <em>Range High</em>}</li>
 * </ul>
 *
 * @see com.rockwellcollins.atc.agree.agree.AgreePackage#getPrimType()
 * @model
 * @generated
 */
public interface PrimType extends Type
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.rockwellcollins.atc.agree.agree.AgreePackage#getPrimType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.rockwellcollins.atc.agree.agree.PrimType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Low Neg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Low Neg</em>' attribute.
   * @see #setLowNeg(String)
   * @see com.rockwellcollins.atc.agree.agree.AgreePackage#getPrimType_LowNeg()
   * @model
   * @generated
   */
  String getLowNeg();

  /**
   * Sets the value of the '{@link com.rockwellcollins.atc.agree.agree.PrimType#getLowNeg <em>Low Neg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Low Neg</em>' attribute.
   * @see #getLowNeg()
   * @generated
   */
  void setLowNeg(String value);

  /**
   * Returns the value of the '<em><b>Range Low</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range Low</em>' attribute.
   * @see #setRangeLow(String)
   * @see com.rockwellcollins.atc.agree.agree.AgreePackage#getPrimType_RangeLow()
   * @model
   * @generated
   */
  String getRangeLow();

  /**
   * Sets the value of the '{@link com.rockwellcollins.atc.agree.agree.PrimType#getRangeLow <em>Range Low</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range Low</em>' attribute.
   * @see #getRangeLow()
   * @generated
   */
  void setRangeLow(String value);

  /**
   * Returns the value of the '<em><b>High Neg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>High Neg</em>' attribute.
   * @see #setHighNeg(String)
   * @see com.rockwellcollins.atc.agree.agree.AgreePackage#getPrimType_HighNeg()
   * @model
   * @generated
   */
  String getHighNeg();

  /**
   * Sets the value of the '{@link com.rockwellcollins.atc.agree.agree.PrimType#getHighNeg <em>High Neg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>High Neg</em>' attribute.
   * @see #getHighNeg()
   * @generated
   */
  void setHighNeg(String value);

  /**
   * Returns the value of the '<em><b>Range High</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range High</em>' attribute.
   * @see #setRangeHigh(String)
   * @see com.rockwellcollins.atc.agree.agree.AgreePackage#getPrimType_RangeHigh()
   * @model
   * @generated
   */
  String getRangeHigh();

  /**
   * Sets the value of the '{@link com.rockwellcollins.atc.agree.agree.PrimType#getRangeHigh <em>Range High</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range High</em>' attribute.
   * @see #getRangeHigh()
   * @generated
   */
  void setRangeHigh(String value);

} // PrimType
