/*
 * Copyright (c) 2023, Collins Aerospace.
 * Developed with the sponsorship of Defense Advanced Research Projects Agency (DARPA).
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this data, 
 * including any software or models in source or binary form, as well as any drawings, specifications, 
 * and documentation (collectively "the Data"), to deal in the Data without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Data, and to permit persons to whom the Data is furnished to do so, 
 * subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Data.
 * 
 * THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
 * LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 * IN NO EVENT SHALL THE AUTHORS, SPONSORS, DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE LIABLE 
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE DATA.
 *
 * Generated by Xtext version 2.30.0.
 */

package com.rockwellcollins.atc.agree.serializer;

import com.google.inject.Inject;
import com.rockwellcollins.atc.agree.services.AgreeGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public abstract class AbstractAgreeSyntacticSequencer extends AbstractSyntacticSequencer {

	protected AgreeGrammarAccess grammarAccess;
	protected AbstractElementAlias match_TermExpr_LeftParenthesisKeyword_18_0_a;
	protected AbstractElementAlias match_TermExpr_LeftParenthesisKeyword_18_0_p;
	protected AbstractElementAlias match_WheneverStatement_OccurKeyword_0_0_0_6_0_or_OccursKeyword_0_0_0_6_1;
	protected AbstractElementAlias match_WheneverStatement_OccurKeyword_1_0_0_7_0_or_OccursKeyword_1_0_0_7_1;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (AgreeGrammarAccess) access;
		match_TermExpr_LeftParenthesisKeyword_18_0_a = new TokenAlias(true, true, grammarAccess.getTermExprAccess().getLeftParenthesisKeyword_18_0());
		match_TermExpr_LeftParenthesisKeyword_18_0_p = new TokenAlias(true, false, grammarAccess.getTermExprAccess().getLeftParenthesisKeyword_18_0());
		match_WheneverStatement_OccurKeyword_0_0_0_6_0_or_OccursKeyword_0_0_0_6_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getWheneverStatementAccess().getOccurKeyword_0_0_0_6_0()), new TokenAlias(false, false, grammarAccess.getWheneverStatementAccess().getOccursKeyword_0_0_0_6_1()));
		match_WheneverStatement_OccurKeyword_1_0_0_7_0_or_OccursKeyword_1_0_0_7_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getWheneverStatementAccess().getOccurKeyword_1_0_0_7_0()), new TokenAlias(false, false, grammarAccess.getWheneverStatementAccess().getOccursKeyword_1_0_0_7_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getAppliesToKeywordsRule())
			return getAppliesToKeywordsToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getInBindingKeywordsRule())
			return getInBindingKeywordsToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getInModesKeywordsRule())
			return getInModesKeywordsToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * AppliesToKeywords:
	 * 	'applies' 'to'
	 * ;
	 */
	protected String getAppliesToKeywordsToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "applies to";
	}
	
	/**
	 * InBindingKeywords:
	 * 	'in' 'binding'
	 * ;
	 */
	protected String getInBindingKeywordsToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "in binding";
	}
	
	/**
	 * InModesKeywords:
	 * 	'in' 'modes'
	 * ;
	 */
	protected String getInModesKeywordsToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "in modes";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_TermExpr_LeftParenthesisKeyword_18_0_a.equals(syntax))
				emit_TermExpr_LeftParenthesisKeyword_18_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_TermExpr_LeftParenthesisKeyword_18_0_p.equals(syntax))
				emit_TermExpr_LeftParenthesisKeyword_18_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_WheneverStatement_OccurKeyword_0_0_0_6_0_or_OccursKeyword_0_0_0_6_1.equals(syntax))
				emit_WheneverStatement_OccurKeyword_0_0_0_6_0_or_OccursKeyword_0_0_0_6_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_WheneverStatement_OccurKeyword_1_0_0_7_0_or_OccursKeyword_1_0_0_7_1.equals(syntax))
				emit_WheneverStatement_OccurKeyword_1_0_0_7_0_or_OccursKeyword_1_0_0_7_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'Get_Property' '(' componentRef=ComponentRef
	 *     (rule start) (ambiguity) '[|' '|]' (rule start)
	 *     (rule start) (ambiguity) '[|' elems+=Expr
	 *     (rule start) (ambiguity) 'enum' '(' enumType=DoubleDotRef
	 *     (rule start) (ambiguity) 'event' '(' port=Expr
	 *     (rule start) (ambiguity) 'exists' binding=NamedID
	 *     (rule start) (ambiguity) 'flatmap' binding=NamedID
	 *     (rule start) (ambiguity) 'floor' '(' expr=Expr
	 *     (rule start) (ambiguity) 'foldl' binding=NamedID
	 *     (rule start) (ambiguity) 'foldr' binding=NamedID
	 *     (rule start) (ambiguity) 'forall' binding=NamedID
	 *     (rule start) (ambiguity) 'if' a=Expr
	 *     (rule start) (ambiguity) 'indices' '(' array=Expr
	 *     (rule start) (ambiguity) 'latched' '(' expr=Expr
	 *     (rule start) (ambiguity) 'pre' '(' expr=Expr
	 *     (rule start) (ambiguity) 'prev' '(' delay=Expr
	 *     (rule start) (ambiguity) 'real' '(' expr=Expr
	 *     (rule start) (ambiguity) 'time' (rule start)
	 *     (rule start) (ambiguity) 'timefall' '(' id=[NamedElement|ID]
	 *     (rule start) (ambiguity) 'timeof' '(' id=[NamedElement|ID]
	 *     (rule start) (ambiguity) 'timerise' '(' id=[NamedElement|ID]
	 *     (rule start) (ambiguity) elm=[NamedElement|DCID]
	 *     (rule start) (ambiguity) op='-'
	 *     (rule start) (ambiguity) op='not'
	 *     (rule start) (ambiguity) recordType=DoubleDotRef
	 *     (rule start) (ambiguity) ref=DoubleDotRef
	 *     (rule start) (ambiguity) val=BooleanLiteral
	 *     (rule start) (ambiguity) val=INTEGER_LIT
	 *     (rule start) (ambiguity) val=REAL_LIT
	 *     (rule start) (ambiguity) {ArraySubExpr.expr=}
	 *     (rule start) (ambiguity) {ArrayUpdateExpr.array=}
	 *     (rule start) (ambiguity) {BinaryExpr.left=}
	 *     (rule start) (ambiguity) {RecordUpdateExpr.record=}
	 *     (rule start) (ambiguity) {SelectionExpr.target=}
	 *     (rule start) (ambiguity) {TagExpr.stem=}
	 
	 * </pre>
	 */
	protected void emit_TermExpr_LeftParenthesisKeyword_18_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'Get_Property' '(' componentRef=ComponentRef
	 *     (rule start) (ambiguity) 'exists' binding=NamedID
	 *     (rule start) (ambiguity) 'flatmap' binding=NamedID
	 *     (rule start) (ambiguity) 'foldl' binding=NamedID
	 *     (rule start) (ambiguity) 'foldr' binding=NamedID
	 *     (rule start) (ambiguity) 'forall' binding=NamedID
	 *     (rule start) (ambiguity) 'if' a=Expr
	 *     (rule start) (ambiguity) 'prev' '(' delay=Expr
	 *     (rule start) (ambiguity) op='-'
	 *     (rule start) (ambiguity) op='not'
	 *     (rule start) (ambiguity) {ArraySubExpr.expr=}
	 *     (rule start) (ambiguity) {ArrayUpdateExpr.array=}
	 *     (rule start) (ambiguity) {BinaryExpr.left=}
	 *     (rule start) (ambiguity) {RecordUpdateExpr.record=}
	 *     (rule start) (ambiguity) {SelectionExpr.target=}
	 *     (rule start) (ambiguity) {TagExpr.stem=}
	 
	 * </pre>
	 */
	protected void emit_TermExpr_LeftParenthesisKeyword_18_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'occur' | 'occurs'
	 *
	 * This ambiguous syntax occurs at:
	 *     effect=Expr (ambiguity) 'during' interval=TimeInterval
	 *     effect=Expr (ambiguity) (rule end)
	 *     excl='exclusively' (ambiguity) 'during' interval=TimeInterval
	 *     excl='exclusively' (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_WheneverStatement_OccurKeyword_0_0_0_6_0_or_OccursKeyword_0_0_0_6_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'occur' | 'occurs'
	 *
	 * This ambiguous syntax occurs at:
	 *     effect=Expr (ambiguity) 'during' interval=TimeInterval
	 *     effect=Expr (ambiguity) (rule end)
	 *     excl='exclusively' (ambiguity) 'during' interval=TimeInterval
	 *     excl='exclusively' (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_WheneverStatement_OccurKeyword_1_0_0_7_0_or_OccursKeyword_1_0_0_7_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
