name: Build and Test Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [opened, reopened, edited]
  workflow_dispatch:

jobs:  
  verify:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install Dependencies
      run: sudo apt-get install -y pandoc
    - name: Compile and Test Maven Project
      run: mvn clean verify
